### ISSUE TITLE
Sístesis u2

### ISSUE THREAD

**Issue by Lizzetee** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Lizzetee#1]
[Sínteisis u2_Lizzete León.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Lizzetee/files/9613056/Sinteisis.u2_Lizzete.Leon.pdf)

**Comment by Rosa218** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
